apiVersion: v1
kind: Secret
metadata:
  name: app-db-credentials
  namespace: default
type: Opaque
stringData:
  username: appuser
  password: S3cr3tP@ssw0rd
---

# Replace namespace and credentials before applying in production.
