apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cloudbeaver-pvc
  namespace: cloudbeaver
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
