apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgadmin-pvc
  namespace: pgadmin
spec:
  storageClassName: nfs-default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

